# Generated by Django 6.0.7 on 2026-07-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='last_violation_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
