# Generated by Django 6.0.7 on 2026-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_last_violation_type_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time_spent_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='violation',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_violation_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(max_length=50),
        ),
    ]
