# Generated by Django 6.0.7 on 2026-07-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_answer_time_spent_seconds_submission_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='game_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='attack_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='defense_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_buff_checkpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='pending_checkpoint_notice',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_boost_charges',
            field=models.IntegerField(default=0),
        ),
    ]
