# Generated by Django 6.0.7 on 2026-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_game_mode_question_image_url_question_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='last_buff_checkpoint',
        ),
        migrations.AddField(
            model_name='submission',
            name='last_buff_milestone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='pending_buff_choice',
            field=models.BooleanField(default=False),
        ),
    ]
