# Generated by Django 6.0.7 on 2026-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_submission_last_buff_checkpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=True),
        ),
    ]
