# Generated by Django 6.0.7 on 2026-08-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exam_randomize_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
    ]
