# Generated by Django 5.2.17 on 2026-09-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_exam_randomize_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_review_answers',
            field=models.BooleanField(default=True),
        ),
    ]
