# Generated by Django 6.1.1 on 2026-10-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_exam_prompt_language_exam_randomize_prompt_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='prompt_language',
            field=models.CharField(choices=[('zh', 'Chinese'), ('ar', 'Arabic'), ('ru', 'Russian'), ('en', 'English')], default='zh', max_length=10),
        ),
    ]
